apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tink-system
resources:
  - hegel
  - kube-vip
  - rufio
  - tink-controller
  - tink-server
  - tink-stack
  - tink-stack-relay
  - namespace.yaml
